### ISSUE TITLE
Issue handling reflections

### ISSUE THREAD

**Issue by spireitepaul** [deane-dremio/dremio-cloner#28]
Hi, 

I'm trying this project for the first time, and I am seeig an eror

python dremio_cloner.py  ..\test_read.json
Traceback (most recent call last):
  File "C:\PythonProjects\dremio-cloner\src\dremio_cloner.py", line 159, in <module>
    main()
  File "C:\PythonProjects\dremio-cloner\src\dremio_cloner.py", line 47, in main
    get_dremio_environment(config)
  File "C:\PythonProjects\dremio-cloner\src\dremio_cloner.py", line 78, in get_dremio_environment
    dremio_data = reader.read_dremio_environment()
  File "C:\PythonProjects\dremio-cloner\src\DremioReader.py", line 57, in read_dremio_environment
    self._read_reflections()
  File "C:\PythonProjects\dremio-cloner\src\DremioReader.py", line 281, in _read_reflections
    reflections = self._dremio_env.list_reflections()['data']
TypeError: 'NoneType' object is not subscriptable

If I change the reflections setting in the JSON config  from Process to Skip, this doesn't have an issue.

I'm running against Dremio 18.1.0 Community Edition

**Comment by deane-dremio** [comment]
@spireitepaul you will see this issue occur if you have the is_community_edition flag set to False in your config file but you are reading from Community Edition. Please change is_community_edition to True and retest.

**Comment by mxmarg** [comment]
Issue has been stale for 1 year
